
package id.co.ogya.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2023-03-01T11:32:46.455+07:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "InvalidInputException", targetNamespace = "http://service.customer.ogya.co.id/")
public class InvalidInputException_Exception extends Exception {

    private id.co.ogya.client.InvalidInputException invalidInputException;

    public InvalidInputException_Exception() {
        super();
    }

    public InvalidInputException_Exception(String message) {
        super(message);
    }

    public InvalidInputException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidInputException_Exception(String message, id.co.ogya.client.InvalidInputException invalidInputException) {
        super(message);
        this.invalidInputException = invalidInputException;
    }

    public InvalidInputException_Exception(String message, id.co.ogya.client.InvalidInputException invalidInputException, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidInputException = invalidInputException;
    }

    public id.co.ogya.client.InvalidInputException getFaultInfo() {
        return this.invalidInputException;
    }
}
