package id.co.ogya.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2023-03-01T15:33:37.088+07:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "TransactionServiceService",
                  wsdlLocation = "file:/C:/Users/Dell/Documents/GitHub/ebanking-exercise/ebanking-client/src/main/resources/client.wsdl",
                  targetNamespace = "http://service.customer.ogya.co.id/")
public class TransactionServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.customer.ogya.co.id/", "TransactionServiceService");
    public final static QName TransactionServicePort = new QName("http://service.customer.ogya.co.id/", "TransactionServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Dell/Documents/GitHub/ebanking-exercise/ebanking-client/src/main/resources/client.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransactionServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Dell/Documents/GitHub/ebanking-exercise/ebanking-client/src/main/resources/client.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransactionServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransactionServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransactionServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TransactionServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TransactionServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TransactionServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TransactionService
     */
    @WebEndpoint(name = "TransactionServicePort")
    public TransactionService getTransactionServicePort() {
        return super.getPort(TransactionServicePort, TransactionService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransactionService
     */
    @WebEndpoint(name = "TransactionServicePort")
    public TransactionService getTransactionServicePort(WebServiceFeature... features) {
        return super.getPort(TransactionServicePort, TransactionService.class, features);
    }

}
