package id.co.ogya.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2023-03-02T14:01:58.062+07:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://service.customer.ogya.co.id/", name = "TransactionService")
@XmlSeeAlso({ObjectFactory.class})
public interface TransactionService {

    @WebMethod
    @Action(input = "http://service.customer.ogya.co.id/TransactionService/cekSaldoRequest", output = "http://service.customer.ogya.co.id/TransactionService/cekSaldoResponse", fault = {@FaultAction(className = InvalidInputException_Exception.class, value = "http://service.customer.ogya.co.id/TransactionService/cekSaldo/Fault/InvalidInputException")})
    @RequestWrapper(localName = "cekSaldo", targetNamespace = "http://service.customer.ogya.co.id/", className = "id.co.ogya.soap.CekSaldo")
    @ResponseWrapper(localName = "cekSaldoResponse", targetNamespace = "http://service.customer.ogya.co.id/", className = "id.co.ogya.soap.CekSaldoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public id.co.ogya.soap.InquiryBalanceResponse cekSaldo(

        @WebParam(name = "arg0", targetNamespace = "")
        id.co.ogya.soap.InquiryBalanceRequest arg0
    ) throws InvalidInputException_Exception;

    @WebMethod
    @Action(input = "http://service.customer.ogya.co.id/TransactionService/kirimRequest", output = "http://service.customer.ogya.co.id/TransactionService/kirimResponse", fault = {@FaultAction(className = InvalidInputException_Exception.class, value = "http://service.customer.ogya.co.id/TransactionService/kirim/Fault/InvalidInputException")})
    @RequestWrapper(localName = "kirim", targetNamespace = "http://service.customer.ogya.co.id/", className = "id.co.ogya.soap.Kirim")
    @ResponseWrapper(localName = "kirimResponse", targetNamespace = "http://service.customer.ogya.co.id/", className = "id.co.ogya.soap.KirimResponse")
    @WebResult(name = "return", targetNamespace = "")
    public id.co.ogya.soap.TransferResponse kirim(

        @WebParam(name = "arg0", targetNamespace = "")
        id.co.ogya.soap.TransferRequest arg0
    ) throws InvalidInputException_Exception;
}
